part of octane.ds;

mixin TypeScale {
  TextStyle heroTitle({
    required Color color,
    double? fontSize,
    FontWeight? fontWeight,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    double? height,
    TextLeadingDistribution? leadingDistribution,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    TextOverflow? overflow,
  }) =>
      TextStyle(
        color: color,
        fontSize: fontSize ?? 180,
        height: height ?? 1,
        fontWeight: fontWeight ?? FontWeight.w900,
        fontFamily: fontFamily ?? 'Fraunces_Standard',
        fontStyle: fontStyle,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        textBaseline: textBaseline,
        leadingDistribution: leadingDistribution,
        fontFamilyFallback: fontFamilyFallback,
        overflow: overflow,
      );

  TextStyle pageTitle({
    required Color color,
    double? fontSize,
    FontWeight? fontWeight,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    double? height,
    TextLeadingDistribution? leadingDistribution,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    TextOverflow? overflow,
  }) =>
      TextStyle(
        color: color,
        fontSize: fontSize ?? 190,
        height: height ?? 1,
        fontWeight: fontWeight ?? FontWeight.w100,
        fontFamily: fontFamily ?? 'Fraunces_Standard',
        fontStyle: fontStyle,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        textBaseline: textBaseline,
        leadingDistribution: leadingDistribution,
        fontFamilyFallback: fontFamilyFallback,
        overflow: overflow,
      );

  TextStyle heading1({
    required Color color,
    double? fontSize,
    FontWeight? fontWeight,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    double? height,
    TextLeadingDistribution? leadingDistribution,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    TextOverflow? overflow,
  }) =>
      TextStyle(
        color: color,
        fontSize: fontSize ?? 79,
        height: height ?? 1,
        fontWeight: fontWeight ?? FontWeight.w900,
        fontFamily: fontFamily ?? 'Fraunces_Standard',
        fontStyle: fontStyle,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        textBaseline: textBaseline,
        leadingDistribution: leadingDistribution,
        fontFamilyFallback: fontFamilyFallback,
        overflow: overflow,
      );

  TextStyle heading2({
    required Color color,
    double? fontSize,
    FontWeight? fontWeight,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    double? height,
    TextLeadingDistribution? leadingDistribution,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    TextOverflow? overflow,
  }) =>
      TextStyle(
        color: color,
        fontSize: fontSize ?? 69,
        height: height ?? 1,
        fontWeight: fontWeight ?? FontWeight.w700,
        fontFamily: fontFamily ?? 'Fraunces_Standard',
        fontStyle: fontStyle,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        textBaseline: textBaseline,
        leadingDistribution: leadingDistribution,
        fontFamilyFallback: fontFamilyFallback,
        overflow: overflow,
      );

  TextStyle heading3({
    required Color color,
    double? fontSize,
    FontWeight? fontWeight,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    double? height,
    TextLeadingDistribution? leadingDistribution,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    TextOverflow? overflow,
  }) =>
      TextStyle(
        color: color,
        fontSize: fontSize ?? 59,
        height: height ?? 1.2,
        fontWeight: fontWeight ?? FontWeight.w300,
        fontFamily: fontFamily ?? 'Fraunces_Standard',
        fontStyle: fontStyle,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        textBaseline: textBaseline,
        leadingDistribution: leadingDistribution,
        fontFamilyFallback: fontFamilyFallback,
        overflow: overflow,
      );

  TextStyle heading4({
    required Color color,
    double? fontSize,
    FontWeight? fontWeight,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    double? height,
    TextLeadingDistribution? leadingDistribution,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    TextOverflow? overflow,
  }) =>
      TextStyle(
        color: color,
        fontSize: fontSize ?? 35,
        height: height ?? 1.2,
        fontWeight: fontWeight ?? FontWeight.w300,
        fontFamily: fontFamily ?? 'Fraunces_Standard',
        fontStyle: fontStyle ?? FontStyle.italic,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        textBaseline: textBaseline,
        leadingDistribution: leadingDistribution,
        fontFamilyFallback: fontFamilyFallback,
        overflow: overflow,
      );

  TextStyle body1({
    required Color color,
    double? fontSize,
    FontWeight? fontWeight,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    double? height,
    TextLeadingDistribution? leadingDistribution,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    TextOverflow? overflow,
  }) =>
      TextStyle(
        color: color,
        fontSize: fontSize ?? 22,
        height: height ?? 1.5,
        fontWeight: fontWeight ?? FontWeight.w500,
        fontFamily: fontFamily ?? 'Cairo',
        fontStyle: fontStyle,
        letterSpacing: letterSpacing,
        wordSpacing: wordSpacing,
        textBaseline: textBaseline,
        leadingDistribution: leadingDistribution,
        fontFamilyFallback: fontFamilyFallback,
        overflow: overflow,
      );

  TextStyle button1({
    required Color color,
    double? fontSize,
    FontWeight? fontWeight,
    FontStyle? fontStyle,
    double? letterSpacing,
    double? wordSpacing,
    TextBaseline? textBaseline,
    double? height,
    TextLeadingDistribution? leadingDistribution,
    String? fontFamily,
    List<String>? fontFamilyFallback,
    TextOverflow? overflow,
  }) =>
      TextStyle(
        color: color,
        fontSize: fontSize ?? 24,
        height: height ?? 1.3,
        fontWeight: fontWeight ?? FontWeight.w600,
        letterSpacing: letterSpacing,
        fontFamily: fontFamily ?? 'Cairo',
        fontStyle: fontStyle,
        wordSpacing: wordSpacing,
        textBaseline: textBaseline,
        leadingDistribution: leadingDistribution,
        fontFamilyFallback: fontFamilyFallback,
        overflow: overflow,
      );
}
