name: octane
description: My site.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  project_redline:
    path: ../ProjectRedline/
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: DMSerifDisplay
      fonts:
        - asset: assets/fonts/dm_serif_display/DMSerifDisplay-Regular.ttf
          weight: 300
        - asset: assets/fonts/dm_serif_display/DMSerifDisplay-Italic.ttf
          weight: 300
          style: italic

    - family: Fraunces_Standard
      fonts:
        - asset: assets/fonts/fraunces/standard/Fraunces_144pt-Thin.ttf
          weight: 100
        - asset: assets/fonts/fraunces/standard/Fraunces_144pt-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/fraunces/standard/Fraunces_144pt-Light.ttf
          weight: 300
        - asset: assets/fonts/fraunces/standard/Fraunces_144pt-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/fraunces/standard/Fraunces_144pt-Regular.ttf
          weight: 400
        - asset: assets/fonts/fraunces/standard/Fraunces_144pt-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/fraunces/standard/Fraunces_144pt-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/fraunces/standard/Fraunces_144pt-Bold.ttf
          weight: 700
        - asset: assets/fonts/fraunces/standard/Fraunces_144pt-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/fraunces/standard/Fraunces_144pt-Black.ttf
          weight: 800
        - asset: assets/fonts/fraunces/standard/Fraunces_144pt-BlackItalic.ttf
          weight: 800
          style: italic

    - family: Fraunces_Soft
      fonts:
        - asset: assets/fonts/fraunces/soft/Fraunces_144pt_Soft-Thin.ttf
          weight: 100
        - asset: assets/fonts/fraunces/soft/Fraunces_144pt_Soft-ThinItalic.ttf
          weight: 100
          style: italic
        - asset: assets/fonts/fraunces/soft/Fraunces_144pt_Soft-Light.ttf
          weight: 300
        - asset: assets/fonts/fraunces/soft/Fraunces_144pt_Soft-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/fraunces/soft/Fraunces_144pt_Soft-Regular.ttf
          weight: 400
        - asset: assets/fonts/fraunces/soft/Fraunces_144pt_Soft-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/fraunces/soft/Fraunces_144pt_Soft-SemiBoldItalic.ttf
          weight: 600
          style: italic
        - asset: assets/fonts/fraunces/soft/Fraunces_144pt_Soft-Bold.ttf
          weight: 700
        - asset: assets/fonts/fraunces/soft/Fraunces_144pt_Soft-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/fraunces/soft/Fraunces_144pt_Soft-Black.ttf
          weight: 800
        - asset: assets/fonts/fraunces/soft/Fraunces_144pt_Soft-BlackItalic.ttf
          weight: 800
          style: italic

    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
          weight: 100
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 200
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 400
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-Black.ttf
          weight: 800
